//! Detection-quality harness.
//!
//! Loads a labeled corpus from `tests/corpus/`, runs the scanner on every
//! document, and compares the results against the ground-truth labels in
//! `tests/corpus/labels.jsonl`.
//!
//! Two metrics are computed and printed on every run:
//!
//! 1. **Recall by sub_category** — for every labeled expected finding in the
//!    `positives/` tree, does the scanner return a match of the right
//!    sub_category whose reported text contains the labeled value?
//!    Labeled finding found → TP, missed → FN. Recall = TP / (TP + FN).
//!
//! 2. **False-positive count by sub_category** — on the `negatives/` tree,
//!    every scanner match whose sub_category appears in that document's
//!    `forbidden` list is a false positive. The metric is the raw count
//!    (there is no natural denominator for a single document).
//!
//! The baseline captured at the initial commit is printed in the output so
//! subsequent PRs can compare. The test does not yet fail on regression —
//! the first job is to make the numbers visible, not to gate on them. A
//! follow-up PR will add explicit thresholds once we know what's achievable.
//!
//! # Coverage gaps in this corpus
//!
//! Two sub_categories we would like to cover are currently **not** in the
//! corpus because GitHub Push Protection refuses to accept strings that
//! match its own secret detectors for them — even for well-known fake
//! values:
//!
//!   * `Stripe Secret Key` (`sk_live_*`) / `Stripe Publishable Key` (`pk_live_*`)
//!   * `Slack Webhook` (`https://hooks.slack.com/services/T.../B.../...`)
//!
//! Those categories are still scanned against the `negatives/` tree
//! (where no such strings exist), so precision on them remains tracked.
//! Recall coverage for them can be added once the repository either
//! adopts a `.github/secret_scanning.yml` allowlist for `tests/corpus/`
//! or the labels are routed through the push-protection bypass URLs.
//! The exclusion is deliberate and the follow-up is tracked.
//!
//! Label schema (one JSON object per line in `labels.jsonl`):
//!
//! ```jsonc
//! // Positive document — every expected finding must fire.
//! {
//!   "path": "positives/pii/ssn_bare.txt",
//!   "expected": [
//!     { "sub_category": "USA SSN", "text": "078-05-1120" }
//!   ]
//! }
//!
//! // Negative document — no match in any listed sub_category may fire.
//! {
//!   "path": "negatives/product_codes_9digit.txt",
//!   "forbidden": ["USA SSN", "USA Passport"]
//! }
//! ```

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use dlpscan::scanner::{scan_text_with_config, ScanConfig};

/// A single ground-truth finding loaded from `labels.jsonl`.
#[derive(Debug, Clone)]
struct ExpectedFinding {
    sub_category: String,
    /// Substring that must appear in the reported match text. Using a
    /// substring comparison (not an exact span match) makes labels
    /// robust against normalization and offset-map details we don't
    /// want the harness to couple to.
    text: String,
}

#[derive(Debug, Clone)]
enum DocLabel {
    Positive {
        path: PathBuf,
        expected: Vec<ExpectedFinding>,
    },
    Negative {
        path: PathBuf,
        forbidden: Vec<String>,
    },
}

/// Very small ad-hoc JSON object parser tailored to the label schema.
///
/// We avoid pulling serde_json into the test just to parse two fields, and
/// the label file is generated by hand so we can assume well-formed input.
/// Each object must be on a single line in `labels.jsonl`. Fields handled:
/// `path` (string), `expected` (array of {sub_category, text}), `forbidden`
/// (array of strings).
fn parse_label_line(line: &str, corpus_root: &Path) -> Option<DocLabel> {
    let line = line.trim();
    if line.is_empty() || line.starts_with("//") {
        return None;
    }

    let path = extract_string_field(line, "\"path\"")?;
    let full_path = corpus_root.join(&path);

    if let Some(arr) = extract_array_field(line, "\"expected\"") {
        let expected = parse_expected_array(arr);
        return Some(DocLabel::Positive {
            path: full_path,
            expected,
        });
    }

    if let Some(arr) = extract_array_field(line, "\"forbidden\"") {
        let forbidden = parse_string_array(arr);
        return Some(DocLabel::Negative {
            path: full_path,
            forbidden,
        });
    }

    None
}

/// Extract a top-level string field value, e.g. `"path":"positives/x.txt"`.
fn extract_string_field(line: &str, key: &str) -> Option<String> {
    let idx = line.find(key)?;
    let rest = &line[idx + key.len()..];
    // Skip over `:` and whitespace.
    let rest = rest.trim_start_matches([':', ' ', '\t']);
    let rest = rest.strip_prefix('"')?;
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

/// Extract the raw contents of a top-level `"field":[...]` array value, not
/// including the surrounding brackets.
fn extract_array_field<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let idx = line.find(key)?;
    let rest = &line[idx + key.len()..];
    let rest = rest.trim_start_matches([':', ' ', '\t']);
    let rest = rest.strip_prefix('[')?;
    let mut depth: i32 = 1;
    let mut in_string = false;
    let mut escape = false;
    for (i, ch) in rest.char_indices() {
        if escape {
            escape = false;
            continue;
        }
        match ch {
            '\\' if in_string => escape = true,
            '"' => in_string = !in_string,
            '[' if !in_string => depth += 1,
            ']' if !in_string => {
                depth -= 1;
                if depth == 0 {
                    return Some(&rest[..i]);
                }
            }
            _ => {}
        }
    }
    None
}

/// Parse an array of `{"sub_category":"…","text":"…"}` objects into a
/// vector of `ExpectedFinding`.
fn parse_expected_array(arr: &str) -> Vec<ExpectedFinding> {
    let mut out = Vec::new();
    let mut i = 0;
    let bytes = arr.as_bytes();
    while i < bytes.len() {
        // Scan to the next `{`
        while i < bytes.len() && bytes[i] != b'{' {
            i += 1;
        }
        if i >= bytes.len() {
            break;
        }
        // Find the matching `}`
        let start = i;
        let mut depth: i32 = 0;
        let mut in_string = false;
        let mut escape = false;
        while i < bytes.len() {
            let c = bytes[i] as char;
            if escape {
                escape = false;
                i += 1;
                continue;
            }
            match c {
                '\\' if in_string => {
                    escape = true;
                }
                '"' => in_string = !in_string,
                '{' if !in_string => depth += 1,
                '}' if !in_string => {
                    depth -= 1;
                    if depth == 0 {
                        i += 1;
                        break;
                    }
                }
                _ => {}
            }
            i += 1;
        }
        let obj = &arr[start..i];
        let sub = extract_string_field(obj, "\"sub_category\"");
        let text = extract_string_field(obj, "\"text\"");
        if let (Some(sub), Some(text)) = (sub, text) {
            out.push(ExpectedFinding {
                sub_category: sub,
                text,
            });
        }
    }
    out
}

/// Parse a simple JSON array of strings.
fn parse_string_array(arr: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = arr;
    while let Some(start) = rest.find('"') {
        let after = &rest[start + 1..];
        if let Some(end) = after.find('"') {
            out.push(after[..end].to_string());
            rest = &after[end + 1..];
        } else {
            break;
        }
    }
    out
}

/// Final per-run report.
struct QualityReport {
    positive_docs: usize,
    negative_docs: usize,
    recall_tp: BTreeMap<String, usize>,
    recall_fn_: BTreeMap<String, usize>,
    /// FP counts per sub_category, aggregated across the negative corpus.
    fp: BTreeMap<String, usize>,
}

impl QualityReport {
    fn new() -> Self {
        Self {
            positive_docs: 0,
            negative_docs: 0,
            recall_tp: BTreeMap::new(),
            recall_fn_: BTreeMap::new(),
            fp: BTreeMap::new(),
        }
    }

    fn print_summary(&self) {
        eprintln!();
        eprintln!("=== Detection Quality Baseline ===");
        eprintln!(
            "Positive corpus: {} docs with labeled findings",
            self.positive_docs
        );
        eprintln!("Negative corpus: {} docs", self.negative_docs);
        eprintln!();

        // Collect every sub_category that appeared in either tree so the
        // row order is deterministic.
        let mut keys: Vec<&String> = self
            .recall_tp
            .keys()
            .chain(self.recall_fn_.keys())
            .collect();
        keys.sort();
        keys.dedup();

        eprintln!("Recall by sub_category:");
        let mut total_tp = 0usize;
        let mut total_fn = 0usize;
        for k in &keys {
            let tp = self.recall_tp.get(*k).copied().unwrap_or(0);
            let fnc = self.recall_fn_.get(*k).copied().unwrap_or(0);
            let total = tp + fnc;
            if total == 0 {
                continue;
            }
            total_tp += tp;
            total_fn += fnc;
            let pct = (tp as f64 / total as f64) * 100.0;
            eprintln!("  {:38}  {:>3}/{:<3}  ({:6.2}%)", k, tp, total, pct);
        }
        let total = total_tp + total_fn;
        let overall = if total == 0 {
            0.0
        } else {
            (total_tp as f64 / total as f64) * 100.0
        };
        eprintln!();
        eprintln!(
            "Overall recall:  {}/{}  ({:.2}%)",
            total_tp, total, overall
        );

        eprintln!();
        eprintln!("False positives on negative corpus:");
        if self.fp.is_empty() {
            eprintln!("  (none)");
        } else {
            let mut fp_keys: Vec<&String> = self.fp.keys().collect();
            fp_keys.sort();
            for k in fp_keys {
                let count = self.fp.get(k).copied().unwrap_or(0);
                if count > 0 {
                    eprintln!("  {:38}  {}", k, count);
                }
            }
        }
        let total_fp: usize = self.fp.values().sum();
        eprintln!();
        eprintln!("Overall FP count: {}", total_fp);
        eprintln!();
    }
}

fn load_corpus(corpus_root: &Path) -> Vec<DocLabel> {
    let labels_path = corpus_root.join("labels.jsonl");
    let raw = fs::read_to_string(&labels_path).unwrap_or_else(|e| {
        panic!(
            "detection-quality harness could not read {}: {}",
            labels_path.display(),
            e
        )
    });
    raw.lines()
        .filter_map(|line| parse_label_line(line, corpus_root))
        .collect()
}

fn run_harness() -> QualityReport {
    let corpus_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus");
    let labels = load_corpus(&corpus_root);

    let config = ScanConfig {
        min_confidence: 0.0,
        ..Default::default()
    };

    let mut report = QualityReport::new();

    for label in &labels {
        match label {
            DocLabel::Positive { path, expected } => {
                report.positive_docs += 1;
                let text = fs::read_to_string(path).unwrap_or_else(|e| {
                    panic!("could not read positive doc {}: {}", path.display(), e)
                });
                let matches = scan_text_with_config(&text, &config).unwrap_or_else(|e| {
                    panic!("scanner error on {}: {}", path.display(), e)
                });

                for exp in expected {
                    // A labeled finding is satisfied if at least one
                    // scanner match has the same sub_category and the
                    // labeled text is a substring of the match's text.
                    let found = matches.iter().any(|m| {
                        m.sub_category == exp.sub_category && m.text.contains(&exp.text)
                    });
                    if found {
                        *report
                            .recall_tp
                            .entry(exp.sub_category.clone())
                            .or_insert(0) += 1;
                    } else {
                        *report
                            .recall_fn_
                            .entry(exp.sub_category.clone())
                            .or_insert(0) += 1;
                        eprintln!(
                            "[detection-quality] MISS: {} / {} in {}",
                            exp.sub_category,
                            exp.text,
                            path.file_name().unwrap_or_default().to_string_lossy()
                        );
                    }
                }
            }

            DocLabel::Negative { path, forbidden } => {
                report.negative_docs += 1;
                let text = fs::read_to_string(path).unwrap_or_else(|e| {
                    panic!("could not read negative doc {}: {}", path.display(), e)
                });
                let matches = scan_text_with_config(&text, &config).unwrap_or_else(|e| {
                    panic!("scanner error on {}: {}", path.display(), e)
                });

                for m in &matches {
                    if forbidden.iter().any(|f| f == &m.sub_category) {
                        *report.fp.entry(m.sub_category.clone()).or_insert(0) += 1;
                        eprintln!(
                            "[detection-quality] FP: {} / {:?} in {}",
                            m.sub_category,
                            m.text,
                            path.file_name().unwrap_or_default().to_string_lossy()
                        );
                    }
                }
            }
        }
    }

    report
}

#[test]
fn detection_quality_baseline() {
    let report = run_harness();
    report.print_summary();

    // First-generation gate: the harness must actually load the corpus
    // and run the scanner. We don't yet fail on specific thresholds —
    // this run captures the baseline numbers so subsequent PRs can
    // compare. A follow-up branch will add recall and FP thresholds
    // once we know what's achievable.
    assert!(report.positive_docs > 0, "no positive docs loaded");
    assert!(report.negative_docs > 0, "no negative docs loaded");
}
