{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dlpscan.fullname" . }}
  labels:
    {{- include "dlpscan.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dlpscan.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8000
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              dlpscan-client: "true"
    - ports:
        - port: 9090
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              app: prometheus
        - namespaceSelector:
            matchLabels:
              name: monitoring
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
