# Ethicalcheck workflow

name: Ethical Check

on:
  push:
    branches:
      - main

jobs:
  ethicalcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Ethical Check
        uses: apisec-inc/ethicalcheck-action@v1
        with:
          # Add any required inputs for the action here
